display: Fix dependency compile error
When enforce compile time product I/F, system_ext module
cannot link to product module and vice versa.
When PRODUCT_PRODUCT_VNDK_VERSION := current, all native modules
in product partition are in the product variant. Adding system_ext_specific
and vendor_available will create system_ext variant and vendor variant.
This will fix the following dependency compile 2 errors:
-Error: MMCapability.cpp:33:10: fatal error: 'qd_utils.h' file not found
libwfdsinksm.so [MMCapability.cpp], installed in SYSTEM_EXT partition
and depends on libqdMetaData [qd_utils.h], accessable in product partition.
Replacing product_specific with system_ext_specific, while enforcing product I/F
will install libqdMetaData in system_ext and variant in product partition

-Error: dependency "libgralloc.qti" of "libqdMetaData" missing variant
libqdMetaData now moved to system_ext. Need to install libgralloc.qti
in system_ext.

Change-Id: Ic4eb768173f2125cee2bb1fa69665b50e8708ea5