Update patch set 2
Patch Set 2:

this commit introduced
hardware/qcom/display-caf/msm8937/sdm/libs/hwc/../../../sdm/include/core/layer_buffer.h:33:10: fatal error: 'color_metadata.h' file not found
#include <color_metadata.h>

Patch-set: 2