composer: Use getpagesize() instead of PAGE_SIZE
Required for targets that have VSR_VENDOR_API_LEVEL >= 35.

display/composer/hwc_session.cpp:188:22: error: use of undeclared identifier 'PAGE_SIZE'
  188 |     char uevent_data[PAGE_SIZE] = {};
      |                      ^
1 error generated.

Change-Id: I3a0c2fe5ead48526e2e6b2bab490d8e24e9e0f65