Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> For a body message, you could put
> 
> "Build with clang and fix the resulting errors"
> 
> or something.

Gah, now I know why they cheated before, errors in kernel includes:

generated_kernel_includes/gen/usr/include/media/msm_m
edia_info.h:343:28: error: implicit conversion changes signedness: 'int' to 'unsigned int' [-Werror,-Wsign-conversion]
                stride = MSM_MEDIA_ALIGN(width, alignment);
                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~


Anyway, still fixing.  I may abandon this one and submit a new review since it'll be larger to clean it all up.

Patch-set: 2
Reviewer: Gerrit User 22917 <22917@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>