composer: Use getpagesize() instead of PAGE_SIZE
hardware/qcom-caf/sm8350/display/composer/hwc_session.cpp:117:22: error: use of undeclared identifier 'PAGE_SIZE'
  117 |     char uevent_data[PAGE_SIZE] = {};
      |                      ^
1 error generated.

Change-Id: I3a0c2fe5ead48526e2e6b2bab490d8e24e9e0f65